name = "enclosed-app"
compatibility_date = "2024-08-20"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "notes"
id = "b1329cb8560e49d392bed877c9ac48a2"

[vars]
# https://developers.cloudflare.com/kv/platform/limits/
NOTES_MAX_ENCRYPTED_PAYLOAD_LENGTH = 26214400
